"""update

Revision ID: ca23fb575490
Revises: 
Create Date: 2025-07-05 11:32:08.920734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca23fb575490'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibrations', 'body_type')
    op.add_column('log_records', sa.Column('body_type', sa.String(), nullable=True))
    op.drop_column('log_records', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_records', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('log_records', 'body_type')
    op.add_column('calibrations', sa.Column('body_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
